name: cogo
description: "COGO"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #router
  go_router: ^13.1.0

  # network
  dio: ^5.3.2

  # status manage
  provider: ^6.0.5

  #splash
  flutter_native_splash: ^2.4.1

  #sharedprefernences
  shared_preferences: ^2.0.7

  #svg
  flutter_svg: ^2.0.10+1

  #날 형식 변환
  intl: ^0.18.0

  #구글 로그인
  google_sign_in: ^6.2.1

  #애플 로그인
  sign_in_with_apple: ^7.0.1

  #토큰 저장소
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.2.0

  #DI
  get_it: ^7.7.0

  #모델 만들기
  json_annotation: ^4.9.0

  #달력
  table_calendar: ^3.0.9

  # 직렬화 Freezed
  freezed_annotation: ^2.0.3

  #토스트 메시지
  fluttertoast: ^8.0.9

  # 애니메이션 로티
  lottie: ^2.2.0
  image_picker: ^0.8.7+5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.0.3
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/navigator/
    - assets/icons/3d_img/
    - assets/icons/button/
    - assets/image/
    - assets/lottie/

  fonts:
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
    - family: PretendardLight
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf

flutter_native_splash:
  color: "#ffffff"  # 배경색 설정 (흰색으로 설정)
  image: null       # 이미지 비활성화
  android: true     # Android에서 적용
  ios: true         # iOS에서 적용
  web: false        # 웹에서 스플래시 화면을 사용하지 않도록 설정